
const config={eventStart:'2026-07-02',currentDay:1};
function getDayNumber(){const start=new Date(config.eventStart+'T00:00:00');const now=new Date();const diff=Math.floor((now-start)/(1000*60*60*24))+1;return Math.min(7,Math.max(1,diff||config.currentDay));}
function goToday(){location.href=`day${getDayNumber()}.html`;}
function markActive(){const here=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-nav]').forEach(a=>{if(a.getAttribute('href')===here)a.classList.add('active')})}
async function loadJSON(path){const r=await fetch(path);return await r.json()}
function footer(){document.querySelectorAll('[data-footer]').forEach(el=>el.innerHTML=`<div class="container footer-grid"><div><b>Экстренные контакты</b><br>Оргкомитет / медики / забота</div><div><b>IT-служба</b><br>Технические вопросы по сайту</div><div><b>Видеомедиа</b><br>Фото, видео, альбомы</div><div><b>Почта проекта</b><br>уточнить у организаторов</div></div>`)}
async function renderServices(){const box=document.querySelector('[data-services]');if(!box)return;const data=await loadJSON('data/services.json');box.innerHTML=data.map(x=>`<article class="person-card"><img src="${x.image}" alt="${x.title}"><div class="body"><span class="tag">${x.tag}</span><h3>${x.title}</h3><p>${x.subtitle}</p></div></article>`).join('')}
async function renderDistricts(){const box=document.querySelector('[data-districts]');if(!box)return;const data=await loadJSON('data/districts.json');box.innerHTML=data.map(x=>`<article class="person-card"><img src="${x.image}" alt="${x.title}"><div class="body"><span class="tag">${x.tag}</span><h3>${x.title}</h3><p>${x.subtitle}</p></div></article>`).join('')}
async function renderFAQ(){const box=document.querySelector('[data-faq]');if(!box)return;const data=await loadJSON('data/faq.json');box.innerHTML=data.map((x,i)=>`<div class="faq-item"><button class="faq-q">${x.q}</button><div class="faq-a">${x.a}</div></div>`).join('');box.querySelectorAll('.faq-q').forEach(btn=>btn.onclick=()=>btn.parentElement.classList.toggle('open'))}
async function renderMaterials(){const box=document.querySelector('[data-materials]');if(!box)return;const data=await loadJSON('data/materials.json');box.innerHTML=data.map(cat=>`<section class="content-block"><h3>${cat.category}</h3>${cat.items.map(i=>`<p><a href="${i.url}">↗ ${i.title}</a></p>`).join('')}</section>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{markActive();footer();renderServices();renderDistricts();renderFAQ();renderMaterials();const t=document.querySelector('[data-today-link]');if(t)t.onclick=e=>{e.preventDefault();goToday()}})
